name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Deploy static files to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Switch to an orphan gh-pages branch
          git switch --orphan gh-pages

          # Remove all existing files
          git rm -rf . --ignore-unmatch

          # Copy static files to the root
          cp -r ./* .  # Adjust `./` if files are in a specific folder like `static/`

          # Add and commit changes
          git add .
          git commit -m "Deploy static site to GitHub Pages"

          # Force-push to gh-pages branch
          git push --force origin gh-pages
