name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # Required to push to the gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and build the project
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      # Step 3: Deploy the static files to gh-pages
      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a new branch for GitHub Pages
          git switch --orphan gh-pages

          # Remove all existing files (if any) from the branch
          git rm -rf . --ignore-unmatch

          # Copy the static files to the root
          cp -r ./out/* .  # Adjust "./out" to your build output directory

          # Add and commit changes
          git add .
          git commit -m "Deploy to GitHub Pages"

          # Force-push to the gh-pages branch
          git push --force origin gh-pages
