name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./out # Replace with your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: all # This downloads the artifact to the 'all' directory

      - name: Merge files
        run: |
          # Create the 'dist' directory
          mkdir dist
          # Move all content from 'all/*/dist/*' to the 'dist' directory
          mv all/*/dist/* ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
       