name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Deploy Pre-Built Files to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Switch to gh-pages branch
          git switch --orphan gh-pages

          # Remove any existing files
          git rm -rf . --ignore-unmatch

          # Copy all files from the repository root to the deployment
          cp -R ./public/* .

          # Add and commit all files
          git add .
          git commit -m "Deploy static site to GitHub Pages"

          # Push to gh-pages branch
          git push --force origin gh-pages
